/-
specmut Lean → IR exporter.

Reads a Lean 4 source file, elaborates it via the standard frontend,
and emits an IR JSON document conforming to §3.3 of the proposal:
separate arrays for sorts, constructors, functions, predicates, and
theorems.  Each constant's signature is decomposed via the forall-chain
of its elaborated type.

Invocation:
  lean --run specmut_export.lean <target.lean>

Phase A milestone 2: schema-shaped output, no IRExpr translation yet
(predicate bodies and theorem conclusions are emitted as a placeholder
`{"kind": "unsupported"}` node).  Equation lemmas and hypothesis
splitting land in M3/M4.
-/
import Lean
open Lean Elab

namespace Specmut.Export

/-! ## Filters -/

/--
Components of a Name that Lean's elaborator generates for inductive
helpers, recursors, equation/unfold lemmas, and size-of definitions.
Drop anything whose name path contains one of these.
-/
def isAuxNameComponent (s : String) : Bool :=
  s == "rec"            || s == "recOn"          || s == "brecOn"        ||
  s == "below"          || s == "ibelow"         || s == "binductionOn"  ||
  s == "casesOn"        ||
  s == "noConfusion"    || s == "noConfusionType"||
  s == "inj"            || s == "injEq"          ||
  s == "sizeOf_spec"    || s == "ctorIdx"        || s == "ctorElim"      ||
  s == "ctorElimType"   || s == "elim"           ||
  s == "eq_def"         || s == "eq_unfold"      ||
  s.startsWith "_sizeOf_"

partial def hasAuxNameComponent : Name → Bool
  | .anonymous => false
  | .str p s   => isAuxNameComponent s || hasAuxNameComponent p
  | .num p _   => hasAuxNameComponent p

def isUserDecl (env : Environment) (name : Name) : Bool :=
  env.getModuleIdxFor? name |>.isNone

def isAutoGenerated (env : Environment) (name : Name) : Bool :=
  name.isInternalDetail || isAuxRecursor env name || hasAuxNameComponent name

/-! ## Phase G: extended noise filters

Suppresses the type-class instance plumbing, decidability/repr/hashable/
inhabited helpers, and stdlib re-exports that `@[deriving …]` and the
elaborator inject around user code.  Without these checks a single
`@[deriving Repr, DecidableEq, BEq, Hashable]` on an inductive can leak
~15 constants into the IR and bloat the model space at slicing time. -/

/-- Substring contains, on `Name` rendered as a dotted path. -/
private def nameContains (n : Name) (sub : String) : Bool :=
  let s := n.toString
  ((s.splitOn sub).length) > 1

/-- A name that the user's own code is exceedingly unlikely to produce
    in a stdlib-only Lean file but the elaborator routinely auto-generates
    for type-class instances. -/
def isTypeClassInstanceName (name : Name) : Bool :=
  let s := name.toString
  s.startsWith "inst"
  -- substring patterns catch namespaced variants like `Foo.instReprNat`
  || nameContains name "instRepr"
  || nameContains name "instDecidable"
  || nameContains name "instBEq"
  || nameContains name "instOrd"
  || nameContains name "instHashable"
  || nameContains name "instInhabited"
  || nameContains name "instToString"

/-- Repr / Format pretty-printing plumbing. -/
def isReprRelated (name : Name) : Bool :=
  nameContains name "Repr"
  || nameContains name "reprStr"
  || nameContains name "toFormat"
  || nameContains name "Std.Format"

/-- Decidability helpers Lean inserts around `@[deriving DecidableEq]`. -/
def isDecidableHelper (name : Name) : Bool :=
  let s := name.toString
  s.startsWith "Decidable"
  || nameContains name "decEq"
  || nameContains name "decidable_of"

/-- Coercion plumbing. -/
def isCoercionHelper (name : Name) : Bool :=
  nameContains name "CoeSort"
  || nameContains name "CoeHTCoe"
  || nameContains name "CoeHead"
  || nameContains name "CoeTail"
  || nameContains name "Coe.coe"

/-- Hashable instances and dictionaries. -/
def isHashHelper (name : Name) : Bool :=
  nameContains name "Hashable"

/-- Inhabited / default-value plumbing. -/
def isInhabitedHelper (name : Name) : Bool :=
  nameContains name "Inhabited"

/-- ToString instances and dictionaries. -/
def isToStringRelated (name : Name) : Bool :=
  nameContains name "ToString"
  || nameContains name "toString"

/-- Stdlib re-exports we never want as IR sorts/functions. -/
def isStdlibReExport (name : Name) : Bool :=
  let s := name.toString
  s.startsWith "Std."
  || s.startsWith "IO."
  || s.startsWith "System."
  || s.startsWith "EStateM."

/-- True iff `name`'s elaborated type ends in a registered type-class
    application — catches instances that don't follow the `inst*`
    naming convention. -/
def isSynthInstance (env : Environment) (name : Name) : Bool :=
  match env.find? name with
  | none => false
  | some ci =>
    let rec stripForall : Expr → Expr
      | .forallE _ _ body _ => stripForall body
      | e => e
    let codomain := stripForall ci.type
    match codomain.getAppFn with
    | .const cn _ => isClass env cn
    | _ => false

/-- Phase G master suppression check.  True iff the constant is noise the
    user's spec does not depend on. -/
def isPhaseGNoise (env : Environment) (name : Name) : Bool :=
  isTypeClassInstanceName name
  || isReprRelated name
  || isDecidableHelper name
  || isCoercionHelper name
  || isHashHelper name
  || isInhabitedHelper name
  || isToStringRelated name
  || isStdlibReExport name
  || isSynthInstance env name

/-! ## Expression → sort-name -/

/--
Turn an `Expr` representing a type into a flat sort identifier.
This is the Phase A name-mangling rule, designed to round-trip cleanly
through the Rust translator:

  * `Nat`       ↦ `"Nat"`
  * `List Nat`  ↦ `"List_Nat"`
  * `Prop`/`Type` ↦ `"_Sort"` (placeholder)
  * bound/free/meta vars ↦ `"_Param"` placeholder
  * anything we don't recognise ↦ `"_Unknown"`

Phase B refines this against a registered semantic-bridge table.
-/
partial def sortNameOf : Expr → String
  | .const c _ => c.toString.replace "." "_"
  | .app f a   => sortNameOf f ++ "_" ++ sortNameOf a
  | .sort _    => "_Sort"
  | .bvar _    => "_Param"
  | .fvar _    => "_Param"
  | .mvar _    => "_Param"
  | _          => "_Unknown"

/-! ## Forall-chain decomposition -/

structure Param where
  name : String   -- binder name (or `_` if anonymous)
  sort : String   -- sort identifier
  deriving Repr

/--
True iff `s` contains `sub` as a substring (any non-empty occurrence).
-/
def stringContains (s sub : String) : Bool :=
  ((s.splitOn sub).length) > 1

/--
Pretty-print a binder `Name`, stripping Lean's macro-hygienic adornments.
Lean wraps macro-introduced binders with markers like `._@.<file>._hyg.<n>`
or `._hyg.<n>` — for downstream consumption we want either the user-visible
base or `_` for fully synthetic names.
-/
partial def paramNameOf (n : Name) : String :=
  if n == .anonymous then "_"
  else
    let s := n.toString
    if s.startsWith "x._@" || s.startsWith "_"
       || stringContains s "._@." || stringContains s "._hyg." then "_"
    else s

/--
Strip all `Expr.forallE` binders off `t`, returning their decomposed
`Param` records and the final codomain expression.
-/
partial def decomposeForall : Expr → (Array Param × Expr)
  | .forallE bname btype body _ =>
      let (rest, codomain) := decomposeForall body
      let here : Param := { name := paramNameOf bname, sort := sortNameOf btype }
      (#[here] ++ rest, codomain)
  | e => (#[], e)

/--
Skip the first `n` `forallE` binders, returning the body.  Used to
discard type parameters of parametric inductives before decomposing
constructor field types.
-/
partial def stripBinders (n : Nat) (e : Expr) : Expr :=
  if n == 0 then e
  else match e with
       | .forallE _ _ body _ => stripBinders (n - 1) body
       | other               => other

/--
Skip the first `n` lambda binders. Used on a predicate's *value*
(`fun p₁ p₂ … => body`) to expose the propositional body.
-/
partial def stripLambdas (n : Nat) (e : Expr) : Expr :=
  if n == 0 then e
  else match e with
       | .lam _ _ body _ => stripLambdas (n - 1) body
       | other           => other

/-! ## Expression → IRExpr translation -/

/--
Walk an application chain and return `(head, args)` in order. For
`f a b c`, returns `(f, [a, b, c])`.
-/
partial def peelApp : Expr → (Expr × Array Expr)
  | .app f a =>
      let (head, args) := peelApp f
      (head, args.push a)
  | e => (e, #[])

/--
Lean encodes the literal `42` as `@OfNat.ofNat α 42 inst` whose third
explicit slot carries an `Expr.lit (.natVal 42)`. Recognize that shape
and return the natural value if present.
-/
def asNatLit? (head : Expr) (args : Array Expr) : Option Nat :=
  if head.isConstOf ``OfNat.ofNat && args.size ≥ 2 then
    match args[1]! with
    | .lit (.natVal n) => some n
    | _ => none
  else none

/-- Stable JSON node for "we didn't translate this; here's a description". -/
def jUnsupported (description : String) : Json :=
  Json.mkObj [("kind", Json.str "unsupported"), ("description", Json.str description)]

/--
Translate an elaborated `Expr` into the §3.3 IRExpr JSON.

`ctx` is the de Bruijn binder name stack — `ctx[0]` is the most-recently-bound
variable, matching Lean's `Expr.bvar` indexing.  Connectives, equality,
ordering, membership, quantifiers, and named application are recognised;
anything else (sorts, projections, metavariables, lambdas inside types,
literals other than Nat) becomes an `unsupported` node.
-/
partial def translateExpr (ctx : List String) (e : Expr) : Json :=
  match e with
  | .bvar i =>
      match ctx[i]? with
      | some name => Json.mkObj [("kind", Json.str "var"), ("name", Json.str name)]
      | none      => jUnsupported s!"loose bvar #{i}"
  | .fvar id =>
      Json.mkObj [("kind", Json.str "var"), ("name", Json.str id.name.toString)]
  | .mdata _ inner => translateExpr ctx inner
  | .const c _ => translateConst ctx c #[]
  | .app .. =>
      let (head, args) := peelApp e
      match head with
      | .const c _ => translateConst ctx c args
      | _          => jUnsupported s!"non-const head: {head.dbgToString}"
  | .forallE bname btype body _ =>
      let nm  := paramNameOf bname
      let bodyIR := translateExpr (nm :: ctx) body
      if !body.hasLooseBVar 0 then
        Json.mkObj [
          ("kind",  Json.str "implies"),
          ("left",  translateExpr ctx btype),
          ("right", bodyIR)
        ]
      else
        Json.mkObj [
          ("kind", Json.str "forall"),
          ("var",  Json.str nm),
          ("sort", Json.str (sortNameOf btype)),
          ("body", bodyIR)
        ]
  | .lit (.natVal n) =>
      Json.mkObj [("kind", Json.str "nat_lit"), ("value", Json.num n)]
  | .lit (.strVal s) =>
      Json.mkObj [("kind", Json.str "app"), ("fn", Json.str s!"\"{s}\""), ("args", Json.arr #[])]
  | .sort _ => jUnsupported "Sort-level expression in IR position"
  | .lam .. => jUnsupported "unexpected lambda in proposition"
  | .letE .. => jUnsupported "let-expression"
  | .proj _ _ _ => jUnsupported "projection"
  | .mvar _ => jUnsupported "metavariable"
where
  /--
  Dispatch on a known connective head, or fall back to `app` form.
  `args` are the full positional arguments (including type/instance
  arguments).  Connective recognition skips type/instance slots so the
  emitted IR carries only semantically meaningful children.
  -/
  translateConst (ctx : List String) (c : Name) (args : Array Expr) : Json := Id.run do
    -- Constants with zero args.
    if c == ``True  then return Json.mkObj [("kind", Json.str "true")]
    if c == ``False then return Json.mkObj [("kind", Json.str "false")]
    -- Binary propositional connectives.
    if c == ``And && args.size == 2 then
      return mkBinary "and"  (translateExpr ctx args[0]!) (translateExpr ctx args[1]!)
    if c == ``Or && args.size == 2 then
      return mkBinary "or"   (translateExpr ctx args[0]!) (translateExpr ctx args[1]!)
    if c == ``Iff && args.size == 2 then
      return mkBinary "iff"  (translateExpr ctx args[0]!) (translateExpr ctx args[1]!)
    if c == ``Not && args.size == 1 then
      return Json.mkObj [("kind", Json.str "not"), ("body", translateExpr ctx args[0]!)]
    -- Equality / inequality: `@Eq α x y`, `@Ne α x y`.
    if c == ``Eq && args.size == 3 then
      return mkBinary "eq"  (translateExpr ctx args[1]!) (translateExpr ctx args[2]!)
    if c == ``Ne && args.size == 3 then
      return mkBinary "neq" (translateExpr ctx args[1]!) (translateExpr ctx args[2]!)
    -- Ordering via type-class projection: `@LE.le α inst x y`, `@LT.lt α inst x y`.
    if c == ``LE.le && args.size == 4 then
      return mkBinary "leq" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
    if c == ``LT.lt && args.size == 4 then
      return mkBinary "lt"  (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
    -- Membership: `@Membership.mem α β inst x c` (5 args).
    if c == ``Membership.mem && args.size == 5 then
      return Json.mkObj [
        ("kind",       Json.str "mem"),
        ("element",    translateExpr ctx args[3]!),
        ("collection", translateExpr ctx args[4]!)
      ]
    -- Existential: `@Exists.{u} α (fun x : α => body)`.
    if c == ``Exists && args.size == 2 then
      match args[1]! with
      | .lam bname btype body _ =>
          let nm := paramNameOf bname
          return Json.mkObj [
            ("kind", Json.str "exists"),
            ("var",  Json.str nm),
            ("sort", Json.str (sortNameOf btype)),
            ("body", translateExpr (nm :: ctx) body)
          ]
      | _ => pure ()    -- fall through to generic app form
    -- Numeric literal sugar: `@OfNat.ofNat α n inst` → bare numeric `app`.
    if let some n := asNatLit? (.const c []) args then
      return Json.mkObj [("kind", Json.str "nat_lit"), ("value", Json.num n)]
    -- Heterogeneous binary operators: `@HOp.hOp α β γ inst x y` (6 args).
    -- Strip the four type/instance slots, keep `x y`, and rename to the
    -- standard FOL function symbol.
    if args.size == 6 then
      if c == ``HAdd.hAdd then return mkApp "add" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
      if c == ``HSub.hSub then return mkApp "sub" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
      if c == ``HMul.hMul then return mkApp "mul" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
      if c == ``HDiv.hDiv then return mkApp "div" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
      if c == ``HMod.hMod then return mkApp "mod" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
      if c == ``HPow.hPow then return mkApp "pow" (translateExpr ctx args[4]!) (translateExpr ctx args[5]!)
    -- Homogeneous binary operators: `@Op.op α inst x y` (4 args).
    if args.size == 4 then
      if c == ``Add.add then return mkApp "add" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
      if c == ``Sub.sub then return mkApp "sub" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
      if c == ``Mul.mul then return mkApp "mul" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
      if c == ``Div.div then return mkApp "div" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
      if c == ``Mod.mod then return mkApp "mod" (translateExpr ctx args[2]!) (translateExpr ctx args[3]!)
    -- Default: opaque application of the named symbol.
    return Json.mkObj [
      ("kind", Json.str "app"),
      ("fn",   Json.str c.toString),
      ("args", Json.arr (args.map (translateExpr ctx)))
    ]
  mkBinary (kind : String) (l r : Json) : Json :=
    Json.mkObj [("kind", Json.str kind), ("left", l), ("right", r)]
  mkApp (fn : String) (a b : Json) : Json :=
    Json.mkObj [("kind", Json.str "app"), ("fn", Json.str fn), ("args", Json.arr #[a, b])]

/-! ## IR-record types (the on-the-wire shape) -/

structure SortDecl where
  name      : Name
  kind      : String     -- "inductive" (Phase A: only inductive sorts surfaced)
  numParams : Nat
  numCtors  : Nat
  deriving Repr

structure CtorDecl where
  name   : Name
  sort   : Name          -- parent inductive
  fields : Array String  -- sort identifiers for each field
  deriving Repr

/-- A first-order equation lemma harvested via `Lean.Meta.getEqnsFor?`.
    `vars` are the universally bound variables; `lhs`/`rhs` are the IRExpr
    sides of the propositional equality. -/
structure IREquation where
  vars : Array Param
  lhs  : Json
  rhs  : Json
  deriving Inhabited

structure FnDecl where
  name      : Name
  domain    : Array String
  codomain  : String
  equations : Array IREquation := #[]
  deriving Inhabited

structure PredDecl where
  name      : Name
  params    : Array Param
  body      : Json
  equations : Array IREquation := #[]
  deriving Inhabited

/-- A theorem hypothesis: a Prop-typed binder split off from the theorem's
forall-chain.  `name` is the binder identifier (or `_` for anonymous);
`body` is the IRExpr of the binder's type. -/
structure Hypothesis where
  name : String
  body : Json
  deriving Inhabited

structure ThmDecl where
  name       : Name
  hypotheses : Array Hypothesis := #[]
  conclusion : Json
  deriving Inhabited

structure ExportPayload where
  sorts        : Array SortDecl     := #[]
  constructors : Array CtorDecl     := #[]
  functions    : Array FnDecl       := #[]
  predicates   : Array PredDecl     := #[]
  theorems     : Array ThmDecl      := #[]
  warnings     : Array String       := #[]
  deriving Inhabited

/-! ## Collection -/

/-- The codomain after stripping all forall binders, used for predicate detection. -/
partial def codomain : Expr → Expr
  | .forallE _ _ body _ => codomain body
  | e => e

/-- Process one `ConstantInfo`, dispatching into the appropriate IR record bucket. -/
def addDecl (name : Name) (ci : ConstantInfo)
    (payload : ExportPayload) : ExportPayload :=
  match ci with
  | .inductInfo iv =>
    let s : SortDecl := {
      name
      kind      := "inductive"
      numParams := iv.numParams
      numCtors  := iv.ctors.length
    }
    { payload with sorts := payload.sorts.push s }
  | .ctorInfo cv =>
    -- Constructor type is `∀ (typeParams) (fields…), Inductive typeParams`.
    -- Skip `numParams` outer binders, then decompose the remaining field chain.
    let body := stripBinders cv.numParams ci.type
    let (fields, _codomain) := decomposeForall body
    let c : CtorDecl := {
      name
      sort   := cv.induct
      fields := fields.map (·.sort)
    }
    { payload with constructors := payload.constructors.push c }
  | .thmInfo _ =>
    let t : ThmDecl := { name, conclusion := translateExpr [] ci.type }
    { payload with theorems := payload.theorems.push t }
  | .defnInfo _ =>
    let (params, cod) := decomposeForall ci.type
    if cod.isProp then
      -- Translate the predicate body: the value is a lambda chain over
      -- the params; we push each binder name onto the context and
      -- translate whatever's underneath.  Pattern-matched recursive
      -- predicates expand to `brecOn`/`match_*` — the translator emits
      -- a deep `app` tree for those, which downstream callers should
      -- prefer to ignore in favor of M4's equation lemmas.
      let body := match ci.value? with
        | none => jUnsupported "no value (axiomatic predicate)"
        | some v =>
          let paramNames := params.toList.map (·.name)
          let stripped   := stripLambdas params.size v
          translateExpr (paramNames.reverse) stripped
      let p : PredDecl := { name, params, body }
      { payload with predicates := payload.predicates.push p }
    else
      let f : FnDecl := {
        name
        domain   := params.map (·.sort)
        codomain := sortNameOf cod
      }
      { payload with functions := payload.functions.push f }
  | _ => payload     -- recInfo, axiomInfo, opaqueInfo, quotInfo: dropped

/-- Walk the elaborated environment and accumulate the IR payload. -/
def collect (env : Environment) : ExportPayload := Id.run do
  let mut payload : ExportPayload := {}
  for (name, ci) in env.constants.toList do
    if !isUserDecl env name then continue
    if isAutoGenerated env name then continue
    -- Phase G: drop type-class instances, derive-generated helpers,
    -- and stdlib re-exports before they reach the payload.  The user's
    -- spec doesn't depend on them and they bloat the model space.
    if isPhaseGNoise env name then continue
    payload := addDecl name ci payload
  return payload

/-! ## Equation lemma harvesting (M4)

For each predicate or recursive function, `Lean.Meta.getEqnsFor?` returns
the names of the auto-generated equation lemmas Lean produced from
pattern-match compilation.  We look up each lemma's elaborated type,
decompose `∀ vars, lhs = rhs`, and translate the sides via `translateExpr`.

For non-recursive simple definitions, `getEqnsFor?` returns `none` and we
emit no equations — the predicate's `body` already carries the full
content.  For recursive predicates like `Sorted`, the body is `brecOn`-
shaped (useless for FOL); the equations array carries the semantic
content downstream consumers should rely on. -/

/--
Decompose one equation-lemma type `∀ x₁ … xₙ, lhs = rhs` into the
universally-bound variables and translated IR sides.  If the body
isn't a recognisable `Eq` application, the equation is dropped.
-/
def decomposeEquation? (eqType : Expr) : Option IREquation :=
  let (vars, body) := decomposeForall eqType
  let ctx := vars.toList.map (·.name) |>.reverse
  match body with
  | .app (.app (.app (.const ``Eq _) _α) lhs) rhs =>
      some { vars, lhs := translateExpr ctx lhs, rhs := translateExpr ctx rhs }
  | .app (.app (.const ``Iff _) lhs) rhs =>
      some { vars, lhs := translateExpr ctx lhs, rhs := translateExpr ctx rhs }
  | _ => none

/--
Harvest equation lemmas for `name` via `Lean.Meta.getEqnsFor?`.

`getEqnsFor?` runs in `MetaM` because for recursive definitions it
synthesises the equation lemmas on demand from Lean's internal eqn-getter
registry.  We translate each lemma's type into an `IREquation`.
-/
def harvestEquations (name : Name) : MetaM (Array IREquation) := do
  let some eqnNames ← Lean.Meta.getEqnsFor? name | return #[]
  let env ← getEnv
  let mut out : Array IREquation := #[]
  for eqName in eqnNames do
    if let some ci := env.find? eqName then
      if let some eq := decomposeEquation? ci.type then
        out := out.push eq
  return out

/--
Split a theorem's elaborated type into hypotheses and a conclusion.

Walks the outer `forallE` chain of `thmType`.  Each binder whose type
is propositional (`Meta.isProp`) becomes a `Hypothesis`; the first
non-Prop binder (or the body itself) terminates the split and the
remainder is translated as the `conclusion`.

This matches the standard reading of `theorem t (h₁ : P₁) … (hₙ : Pₙ) : C`
as `H₁ → … → Hₙ → C` — hypotheses are the leading Prop arguments;
universal value parameters (e.g. `(n : Nat)`) appear as `forall` IRExpr
nodes wrapping the conclusion.
-/
partial def splitTheorem (ctx : List String) (thmType : Expr) :
    MetaM (Array Hypothesis × Json) := do
  match thmType with
  | .forallE bname btype body _ =>
      if (← Meta.isProp btype) then
        let nm := paramNameOf bname
        let h : Hypothesis := { name := nm, body := translateExpr ctx btype }
        let (rest, concl) ← splitTheorem (nm :: ctx) body
        return (#[h] ++ rest, concl)
      else
        return (#[], translateExpr ctx thmType)
  | _ => return (#[], translateExpr ctx thmType)

/--
Walk `payload` and attach equations to every predicate and function,
plus split each theorem's leading Prop binders into hypotheses.
Errors from MetaM operations are caught locally so one bad declaration
doesn't sink the whole enrichment pass.
-/
def enrich (payload : ExportPayload) : MetaM ExportPayload := do
  let mut payload := payload
  let mut preds : Array PredDecl := #[]
  for p in payload.predicates do
    let eqs ← try harvestEquations p.name catch _ => pure #[]
    preds := preds.push { p with equations := eqs }
  payload := { payload with predicates := preds }
  let mut fns : Array FnDecl := #[]
  for f in payload.functions do
    let eqs ← try harvestEquations f.name catch _ => pure #[]
    fns := fns.push { f with equations := eqs }
  payload := { payload with functions := fns }
  let mut thms : Array ThmDecl := #[]
  for t in payload.theorems do
    let env ← getEnv
    let some ci := env.find? t.name | thms := thms.push t; continue
    let (hyps, concl) ← try splitTheorem [] ci.type
      catch _ => pure (#[], t.conclusion)
    thms := thms.push { t with hypotheses := hyps, conclusion := concl }
  payload := { payload with theorems := thms }
  return payload

/--
Run a `MetaM` action against `env` and surface either a successful
result or a captured error message.  Used to invoke the equation
harvester from `main` without making the whole script MetaM-typed.
-/
def runInMetaM (env : Environment) (action : MetaM α) : IO (Except String α) := do
  let coreCtx : Core.Context := { fileName := "<specmut_export>", fileMap := FileMap.ofString "" }
  let coreState : Core.State := { env := env }
  try
    let ((a, _metaState), _coreState) ← (action.run {} {}).toIO coreCtx coreState
    return .ok a
  catch e =>
    return .error (toString e)

/-! ## JSON rendering -/

def paramJson (p : Param) : Json :=
  Json.mkObj [("name", Json.str p.name), ("sort", Json.str p.sort)]

def sortJson (s : SortDecl) : Json :=
  Json.mkObj [
    ("name",       Json.str s.name.toString),
    ("kind",       Json.str s.kind),
    ("num_params", Json.num s.numParams),
    ("num_ctors",  Json.num s.numCtors)
  ]

def ctorJson (c : CtorDecl) : Json :=
  Json.mkObj [
    ("name",   Json.str c.name.toString),
    ("sort",   Json.str c.sort.toString),
    ("fields", Json.arr (c.fields.map Json.str))
  ]

def equationJson (eq : IREquation) : Json :=
  Json.mkObj [
    ("vars", Json.arr (eq.vars.map paramJson)),
    ("lhs",  eq.lhs),
    ("rhs",  eq.rhs)
  ]

def fnJson (f : FnDecl) : Json :=
  Json.mkObj [
    ("name",      Json.str f.name.toString),
    ("domain",    Json.arr (f.domain.map Json.str)),
    ("codomain",  Json.str f.codomain),
    ("equations", Json.arr (f.equations.map equationJson))
  ]

def predJson (p : PredDecl) : Json :=
  Json.mkObj [
    ("name",      Json.str p.name.toString),
    ("params",    Json.arr (p.params.map paramJson)),
    ("body",      p.body),
    ("equations", Json.arr (p.equations.map equationJson))
  ]

def hypothesisJson (h : Hypothesis) : Json :=
  Json.mkObj [("name", Json.str h.name), ("body", h.body)]

def thmJson (t : ThmDecl) : Json :=
  Json.mkObj [
    ("name",       Json.str t.name.toString),
    ("hypotheses", Json.arr (t.hypotheses.map hypothesisJson)),
    ("conclusion", t.conclusion)
  ]

def renderDocument (sourceFile : String) (payload : ExportPayload) : Json :=
  Json.mkObj [
    ("version",      Json.num 1),
    ("source_file",  Json.str sourceFile),
    ("sorts",        Json.arr (payload.sorts.map sortJson)),
    ("constructors", Json.arr (payload.constructors.map ctorJson)),
    ("functions",    Json.arr (payload.functions.map fnJson)),
    ("predicates",   Json.arr (payload.predicates.map predJson)),
    ("theorems",     Json.arr (payload.theorems.map thmJson)),
    ("warnings",     Json.arr (payload.warnings.map Json.str))
  ]

end Specmut.Export

open Specmut.Export

def main (args : List String) : IO UInt32 := do
  let path ← match args with
    | [p] => pure p
    | _ => do
        IO.eprintln "usage: lean --run specmut_export.lean <target.lean>"
        return (1 : UInt32)

  initSearchPath (← findSysroot)

  let source ← try IO.FS.readFile path
    catch e => do
      IO.eprintln s!"specmut_export: cannot read '{path}': {e}"
      return (1 : UInt32)

  let inputCtx := Parser.mkInputContext source path
  let (header, parserState, msgs) ← Parser.parseHeader inputCtx
  let (env, msgs) ← processHeader header {} msgs inputCtx

  let cmdState := Command.mkState env msgs {}
  let s ← IO.processCommands inputCtx parserState cmdState
  let finalEnv := s.commandState.env
  let finalMsgs := s.commandState.messages

  let mut payload := collect finalEnv
  let mut warnings : Array String := #[]
  for m in finalMsgs.toList do
    if m.severity == .error then
      let txt ← m.toString
      warnings := warnings.push s!"elaboration error: {txt}"

  -- M4 enrichment: harvest equation lemmas for predicates / recursive
  -- functions, and split theorem hypotheses out of the forall-chain.
  -- Falls back gracefully if MetaM setup fails.
  match ← runInMetaM finalEnv (enrich payload) with
  | .ok p    => payload := p
  | .error e => warnings := warnings.push s!"MetaM enrichment failed: {e}"

  payload := { payload with warnings }

  IO.println (renderDocument path payload).pretty
  return 0
